### ISSUE TITLE
Simple example

### ISSUE THREAD

**Issue by Alex293** [Juanpe/Swift-VIPER-Module#1]
Hi it would be very nice to have a very simple example using it. i.e. just 2 modules that do nothing but show how to load the root one from the app delegate and load another one from it. I'm new to viper and every source have a way to do it so I'd like to know your way because i'm gonna use your template :)

**Comment by Alex293** [comment]
Also do you use generic extension to load your xib or use per module code into the viewProtocol ?

**Comment by Juanpe** [comment]
Hi @Alex293, I think that is a good idea to create an simple example. I labeled as enhancement.
And the second question, the wireframe should initialize your ViewControllers, so wireframe is a good place to load your xib..

**Comment by Alex293** [comment]
I've been using it and I love it !
