### ISSUE TITLE
Can't install ViperModule

### ISSUE THREAD

**Issue by kishore4a2** [Juanpe/Swift-VIPER-Module#10]
Hi i tried to install the viper module with the below line of code in Terminal , but it is throwing an error, can you tell me the process how to install
<img width="571" alt="screen shot 2017-07-30 at 1 10 11 am" src="https://user-images.githubusercontent.com/4446311/28746848-e76065f8-74c4-11e7-98c9-5637148d53ba.png">

**Comment by Juanpe** [comment]
Hi @kishore4a2, this issue closed could help you [https://github.com/Juanpe/Swift-VIPER-Module/issues/7](url)
