### ISSUE TITLE
Error Swift 4

### ISSUE THREAD

**Issue by infinitystar78** [Juanpe/Swift-VIPER-Module#13]
install.swift:58:16: error: subscripts returning String were obsoleted in Swift 4; explicitly construct a String from subscripted result
        return output[output.startIndex ..< lastIndex]

**Comment by xijiangyueal** [comment]
You should replace line 58 with

    return String(output[output.startIndex ..< lastIndex])

**Comment by Juanpe** [comment]
Duplicate issue [#8](https://github.com/Juanpe/Swift-VIPER-Module/issues/8)

**Comment by Juanpe** [comment]
#8

**Comment by Juanpe** [comment]
#
