### ISSUE TITLE
This is not what I want, how to uninstall?

### ISSUE THREAD

**Issue by Franzeyang** [Juanpe/Swift-VIPER-Module#21]

**Comment by o15a3d4l11s2** [comment]
Just go to /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/Templates/Project Templates/iOS/Application and delete the folder named "Module VIPER.xctemplate".

**Comment by Franzeyang** [comment]
Thanks
