### ISSUE TITLE
Simple thoughts on naming

### ISSUE THREAD

**Issue by Alex293** [Juanpe/Swift-VIPER-Module#5]
Hi, I've been testing others viper generator and some use __moduleName__Contracts for the protocol file. I think that nice as this file represent how to interact with the module. Also the protocols name is kinda too generic and could have other uses into projects like the delegate of the module.

**Comment by Juanpe** [comment]
Hi @Alex293, I'm going to improve the names. In the future, you will be able customize the name of components.
