### ISSUE TITLE
error installing with Swift 4

### ISSUE THREAD

**Issue by jorgifumi** [Juanpe/Swift-VIPER-Module#8]
sudo swift install.swift
Password:
install.swift:58:16: error: subscripts returning String were obsoleted in Swift 4; explicitly construct a String from subscripted result
        return output[output.startIndex ..< lastIndex]
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               String(                                )

**Comment by albcc** [comment]
You should replace line 58 with

        return String(output[output.startIndex ..< lastIndex])

**Comment by Juanpe** [comment]
Fixed! ✅

**Comment by KaytenTechnology** [comment]
I face the same problem

**Comment by KaytenTechnology** [comment]
We face the same problem

**Comment by Juanpe** [comment]
@KaytenTechnology  It's already solved 😬
